version: "3.7"

services:

  phpfpm:
    image: bitnami/php-fpm:latest
    container_name: phpfpm
    volumes:
      - ./public:/app

  proxy:
    image: imkulikov/nginx-sticky:latest
    container_name: proxy
    volumes:
      - ./public:/app
      - ./nginx.conf/nginx.proxy.conf:/etc/nginx/conf.d/z-overrides.conf
    ports:
      - 8061:80

  site2:
    image: nginx:alpine
    container_name: site2
    volumes:
      - ./public:/app
      - ./nginx.conf/nginx.site2.conf:/etc/nginx/conf.d/z-overrides.conf

  site3:
    image: nginx:alpine
    container_name: site3
    volumes:
      - ./public:/app
      - ./nginx.conf/nginx.site3.conf:/etc/nginx/conf.d/z-overrides.conf

  site1-loadbalance1:
    image: webserver
    container_name: site1-loadbalance1
    volumes:
      - ../:/var/www/html

  site1-loadbalance2:
    image: webserver
    container_name: site1-loadbalance2
    volumes:
      - ../:/var/www/html

  site1-loadbalance3:
    image: webserver
    container_name: site1-loadbalance3
    volumes:
      - ../:/var/www/html